### ISSUE TITLE
(feat): mask input variable

### ISSUE THREAD

**Issue by lukasmrtvy** [upcmd/up#20]
Would be nice to be able mask input variable, something like:
```
flags:
- masked
```
, ( similar to terraform 0.14 feature ) to prevent outputing this variable to stdout/stderr, its important when are you need to ship logs from upcmd to some elasticsearch, splunk, etc.

Thanks

**Comment by stephencheng** [comment]
Good idea!

I will add this feature

Thanks

**Comment by stephencheng** [comment]
@lukasmrtvy 

I have added the feature you requested, see details: 

source: https://github.com/upcmd/up/blob/master/tests/functests/p0210.yml
doc: https://github.com/upcmd/updocs/blob/master/content-src/security/masked_input.md

Let me know if it's good for your use caes
